apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: idea-board
type: Opaque
stringData:
  DATABASE_URL: "postgresql+psycopg://ideas_user:ideas_pass@postgres.idea-board.svc.cluster.local:5432/ideas"
