apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: idea-board
type: Opaque
stringData:
  DB_HOST: "idea-board-postgres.cwl4aekmih17.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "ideas"
  DB_USER: "puneet_admin"
  DB_PASSWORD: "puneet123"
